package com.xxfbpt.webservice;
//Generated by MyEclipse

public interface IXxfbptwebservice {
	
	public String example(String message) throws Exception;	
	
	/**
	 * 信息平台调度
	 * @param userid 用户id
	 * @param userpwd 用户密码
	 * @param jkid 接口id
	 * @param srcs 输入参数
	 * @return 返回报文如果用户不存在，用默认密钥，其他用每个用户特有的密钥
	 * @throws Exception
	 */
	public String xxptSchuding(String userid, String userpwd, String jkid, String srcs) throws Exception;
	
}